jenkins:
  systemMessage: "Redpanda Playground - Jenkins CI/CD"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: 9615
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
unclassified:
  location:
    url: http://localhost:29080/
