input:
  kafka_franz:
    seed_brokers:
      - redpanda:9092
    topics:
      - playground.pipeline.commands
    consumer_group: connect-nexus-${TOOL_ID}-command
    start_from_oldest: false

pipeline:
  processors:
    - mapping: |
        let event_type = @eventType.string()
        let target_tool = @targetToolId.string()
        root = if $event_type != "NEXUS_SEARCH_COMMAND" || $target_tool != "${TOOL_ID}" {
          deleted()
        } else { this }

output:
  http_client:
    url: "${TOOL_URL}/service/rest/v1/search?repository=${! this.repository }&name=${! this.componentName }"
    verb: GET
    headers:
      Accept: application/json
    basic_auth:
      enabled: true
      username: "${TOOL_USERNAME}"
      password: "${TOOL_CREDENTIAL}"
