apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "playground.fullname" . }}
  labels:
    {{- include "playground.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "playground.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "playground.selectorLabels" . | nindent 8 }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.metrics.path }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profiles }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.spring.datasource.url }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.spring.datasource.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.spring.datasource.password }}
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.spring.kafka.bootstrapServers }}
            - name: SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
              value: {{ .Values.spring.kafka.schemaRegistryUrl }}
            - name: APP_CONNECT_URL
              value: {{ .Values.spring.connect.url }}
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: {{ .Values.spring.otel.endpoint }}
          readinessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: {{ .Values.health.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: {{ .Values.health.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
