ALTER TABLE support_tool ADD COLUMN IF NOT EXISTS health_status VARCHAR(10) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE support_tool ADD COLUMN IF NOT EXISTS health_checked_at TIMESTAMP;
ALTER TABLE support_tool ADD COLUMN IF NOT EXISTS api_token VARCHAR(500);
