apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console
  namespace: argocd
spec:
  project: playground
  sources:
    - repoURL: https://github.com/scofe97/Redpanda-PlayGround.git
      targetRevision: main
      ref: values
    - repoURL: https://charts.redpanda.com
      chart: console
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/infra/k8s/console/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rp-oss
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
